using System.Text;
using ConnectorControl.Core.Tests.TestSupport;

namespace ConnectorControl.Core.Tests;

/// <summary>Byte parity with Apple Foundation output generated by Tests/ConnectorControlCoreTests/GoldenFileTests.swift.</summary>
public class GoldenFileTests
{
    public static TheoryData<string> AllInputs => new(
        Directory.GetFiles(Fixtures.Path("golden/inputs"), "*.json")
            .Select(p => System.IO.Path.GetFileName(p))
            .OrderBy(n => n, StringComparer.Ordinal));

    /// <summary>Swift's testGoldensAreCurrent pins this count inline; the Theory-per-input
    /// shape here needs its own guard so a dropped or forgotten fixture fails loudly instead
    /// of just shrinking the Theory's row count.</summary>
    [Fact]
    public void FourGoldenInputs()
    {
        Assert.Equal(4, Directory.GetFiles(Fixtures.Path("golden/inputs"), "*.json").Length);
    }

    [Theory]
    [MemberData(nameof(AllInputs))]
    public void EncoderFormatMatchesApple(string name)
    {
        var value = JsonValue.Parse(Fixtures.Bytes($"golden/inputs/{name}"));
        AssertSameBytes(Fixtures.Bytes($"golden/encoder/{name}"), value.Serialize());
    }

    [Theory]
    [MemberData(nameof(AllInputs))]
    public void EditorTextMatchesApple(string name)
    {
        var value = JsonValue.Parse(Fixtures.Bytes($"golden/inputs/{name}"));
        AssertSameBytes(Fixtures.Bytes($"golden/editor/{name}"), Encoding.UTF8.GetBytes(value.EditorText()));
    }

    [Theory]
    [MemberData(nameof(AllInputs))]
    public void SerializationFormatMatchesApple(string name)
    {
        var value = JsonValue.Parse(Fixtures.Bytes($"golden/inputs/{name}"));
        AssertSameBytes(Fixtures.Bytes($"golden/serialization/{name}"), AppleJsonWriter.WriteUtf8(value, AppleJsonFormat.Serialization));
    }

    [Theory]
    [MemberData(nameof(AllInputs))]
    public void SerializationCompactFormatMatchesApple(string name)
    {
        var value = JsonValue.Parse(Fixtures.Bytes($"golden/inputs/{name}"));
        AssertSameBytes(Fixtures.Bytes($"golden/serialization-compact/{name}"), AppleJsonWriter.WriteUtf8(value, AppleJsonFormat.SerializationCompact));
    }

    [Theory]
    [MemberData(nameof(AllInputs))]
    public void GoldensReparseToTheSameValue(string name)
    {
        var value = JsonValue.Parse(Fixtures.Bytes($"golden/inputs/{name}"));
        Assert.Equal(value, JsonValue.Parse(Fixtures.Bytes($"golden/encoder/{name}")));
        Assert.Equal(value, JsonValue.Parse(Fixtures.Bytes($"golden/editor/{name}")));
        Assert.Equal(value, JsonValue.Parse(Fixtures.Bytes($"golden/serialization/{name}")));
        Assert.Equal(value, JsonValue.Parse(Fixtures.Bytes($"golden/serialization-compact/{name}")));
    }

    private static void AssertSameBytes(byte[] expected, byte[] actual)
    {
        // Compare as text first for a readable diff, then as bytes for exactness.
        Assert.Equal(Encoding.UTF8.GetString(expected), Encoding.UTF8.GetString(actual));
        Assert.Equal(expected, actual);
    }
}
